services:
  webserver:
    image: nginx:alpine
    container_name: 'project_name-nginx'
    volumes:
      - ./app:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php:
    build: docker/php
    container_name: 'project_name-php83'
    volumes:
      - ./app:/app
      - ./docker/php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf
  mariadb:
    image: mariadb:11.4
    container_name: 'project_name-mariadb114'
    env_file:
      - ./docker.env
    # ports:
    #   - "9907:3306" # For using services like DBeaver
    volumes: 
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/data/logs:/var/lib/mysql/logs
      - ./docker/mariadb/conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD